version: '3.8'

services:
  db:
    image: mongo:6
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: thisPassWillNeverNopeMon19

  amw:
    build: ./
    env_file: [ .env.dev ]
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: "mongodb://root:thisPassWillNeverNopeMon19@db:27017/ahw?authSource=admin"
